- name: Install haproxy package
  package:
    name: haproxy
    state: present

- name: Copy haproxy config File
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
  notify: Restart haproxy LB Service

- name: Start haproxy LB Service
  service:
    name: haproxy
    state: started